### ISSUE TITLE
tweak shell key to customize options for shebang

### ISSUE THREAD

**Issue by shahzebsiddiqui** [HPC-buildtest/schemas#27]
@vsoch 

Currently, buildtest will use the following shebangs when writing the test script

```
#!/bin/bash
#!/bin/sh
```

I propose there should be a mechanism to add options to customize the shebang line. For example running a code in debug mode via ``#!/bin/bash -x`` can be achieved or running in interactive mode ``!#/bin/bash -i`` or login mode ``#!/bin/bash -l``.

I propose the test block be modified as follows

```
version: 0.0.1
shebang_option_autodetect:
  type: script
  description: Auto detect shebang based on shell name 'bash' and add option -l
  shell:
    name: "bash"
    opts: "-l"
  run: |
    hostname
shebang_name:
  type: script
  description: User specifies shebang name and injected as is into the script along with the shebang option.
  shell:
    shebang: "#!/bin/bash"
    opts: "-l"
  run: |
    hostname
```

The difference between ``name`` and ``shebang`` is that name will have ``enum`` of ``[bash, sh]`` so user can select the shell and buildtest will detect the shebang. 

The user can also specify ``shebang`` key to tweak the exact path to shebang line in test. In this case, buildtest will not perform auto-detection, but we leave it up to the user to specify the path. buildtest should atleast do a sanity check to see if file path exist before writing test.

It is possible that user can specify ``/usr/bin/env bash`` see https://linuxize.com/post/bash-shebang/ which can pick up the ``bash`` binary from user $PATH. It's unlikely anyone will ever do this, but this would be something user can specify when using ``shebang`` key word.

If this makes sense i can take a shot at making this change in the script schema.

**Comment by vsoch** [comment]
I think it would make sense to instead just allow the args to be specified with the shell. Then we would parse them when we parse it. It reads much more nicely like that:

```
version: 0.0.1
shebang_option_autodetect:
  type: script
  description: Auto detect shebang based on shell name 'bash' and add option -l
  shell: "bash -l"
```

**Comment by vsoch** [comment]
With my suggestion, the env command using bash would also work - env would be found as the binary, and the rest parsed as args. I don't like the specification of shebang - it seems redundant since the user can define whatever shell they want (and the shebang is added). If you showed me docs like the above I'd just be super confused.

**Comment by shahzebsiddiqui** [comment]
> I think it would make sense to instead just allow the args to be specified with the shell. Then we would parse them when we parse it. It reads much more nicely like that:
> 
> ```
> version: 0.0.1
> shebang_option_autodetect:
>   type: script
>   description: Auto detect shebang based on shell name 'bash' and add option -l
>   shell: "bash -l"
> ```

So with this example, this may seem too simple and confusing for a few reasons to me and the users
1. Does buildtest figure out shebang line based on ``shell: "bash -l"``
2. With ``shell: "bash -l"`` you allow user to specify any string they want because now we removed the ``enum`` to allow options.
3. How would user specify an alternate shebang for path to ``bash`` do they do ``shell: /path/to/bash`` or ``shell: /usr/bin/env bash`` or ``shell: bash``. 

I like the enum on ``shell`` how we have originally, but we also need way to pass options, hence i propose change ``shell`` to an object and have ``name`` and ``opts``. Another option is keep ``shell`` as is and add a new key maybe ``shell_opts``.

Here is an examples with just adding ``shell_opts``.

```
version: 0.0.1
shebang_option_autodetect:
  type: script
  description: Auto detect shebang based on shell name 'bash' and add option -l
  shell: "bash"
  shell_opts: "-l"
```

With our current approach we don't have way to specify an arbitrary shebang path, I don't see it being used often so maybe we ditch this for now.

**Comment by vsoch** [comment]
> Does buildtest figure out shebang line based on shell: "bash -l"
 
Yes. The first thing provided, whether it's bash or env, is always evaluated to the full path, and the rest treated as args to it, whether they be "bash" as an input to env, or "-l" as a command to bash.

> How would user specify an alternate shebang for path to bash do they do shell: /path/to/bash or shell: /usr/bin/env bash or shell: bash.

Just exactly how they want it. Either of these would work.

```yaml
version: 0.0.1
shebang_option_autodetect:
  type: script
  description: Auto detect shebang based on shell name 'bash' and add option -l
  shell: "env bash"
```


```yaml
version: 0.0.1
shebang_option_autodetect:
  type: script
  description: Auto detect shebang based on shell name 'bash' and add option -l
  shell: "/usr/bin/env bash"
```
The parser evaluates the first to get a full path, that is formatted into the shebang, and whatever arguments follow (bash or -l or whatever) are honored. The solution I present meets all use cases, it clear and simple, and not confusing.

**Comment by vsoch** [comment]
@shahzebsiddiqui it should work and solve this issue to just honor including additional arguments to the shell. You don't need extra definitions in a schema or some complicated parsing.

**Comment by shahzebsiddiqui** [comment]
Okay i think this is not going to work since ``shell`` is tied into how command is executed and how environment variable section is picked up. Here is part of the logs, some of which will give some insight

```
2020-04-19 12:28:00,795 [base.py:343 - get_environment() ] - [WARNING] bash -l is not supported, skipping environment variables.
2020-04-19 12:28:00,795 [base.py:540 - _write_test() ] - [INFO] Opening Test File for Writing: /mxg-hpc/users/ssi29/tutorials/apps/openacc/.buildtest/vecadd/vecadd_gnu.sh
2020-04-19 12:28:00,796 [base.py:552 - _write_test() ] - [DEBUG] Applying permission 755 to /mxg-hpc/users/ssi29/tutorials/apps/openacc/.buildtest/vecadd/vecadd_gnu.sh so that test can be executed
2020-04-19 12:28:00,796 [base.py:453 - run_tests() ] - [DEBUG] Changing to directory /mxg-hpc/users/ssi29/tutorials/apps/openacc/.buildtest/vecadd
2020-04-19 12:28:00,796 [base.py:458 - run_tests() ] - [DEBUG] Running Test via command: bash -l /mxg-hpc/users/ssi29/tutorials/apps/openacc/.buildtest/vecadd/vecadd_gnu.sh
```

The following buildspec resulted in the entire environment section to be skipped

```
(buildtest-framework) ssi29@ag-mxg-hulk090> cat vecadd.yml
version: 0.0.1

vecadd_gnu:
  type: script
  description: Vector Addition example with GNU compiler
  shell: "bash -l"
  env:
    cc: gcc
    cflags: -fopenacc
    ldflags: -lm
    exe: vecAdd
    srcdir: $WORK/tutorials/apps/openacc/src
  run: |
    module load gcc
    $cc $cflags -o $exe $srcdir/vecAdd.c $ldflags
    ./$exe
(buildtest-framework) ssi29@ag-mxg-hulk090> cat .buildtest/vecadd/vecadd_gnu.sh
#!/bin/bash
module load gcc
$cc $cflags -o $exe $srcdir/vecAdd.c $ldflags
./$exe

```

We need to decouple the shell shebang line vs how test is run.

**Comment by shahzebsiddiqui** [comment]
This is where shebang is written https://github.com/buildntest/buildtest/blob/devel/buildtest/buildsystem/base.py#L569

**Comment by vsoch** [comment]
This isn't a flaw in the idea, it's a bug in the implementation. The shebang should not include the entirety of shell, just the executable from it. In the same way the command is parsed with shutil.which(), the shell is the first (0 index) and then the rest are args. for the actual call.

**Comment by shahzebsiddiqui** [comment]
Yes i understand the issue and it's trivial. buildtest should support modification of shebang line and how test is run. For shell scripts we can run the script directly since it's executable given that shebang is correctly generated.

The ``#!/bin/bash -l`` is equivalent to running ``bash -l script.sh`` both of which should be supported. Furthermore, user should have more flexibility on how test are dispatched, let's say they want to time their scripts they can do ``time script.sh``. I think the test dispatch would need to be independent to ``shell``, let's say in the executor types in buildtest settings or use of ``executor`` in the Buildspec. It's not clear at the moment.

**Comment by vsoch** [comment]
oh the issue is with the schemas repo - that's why I couldn't find it!

Two questions:

1. Why not just use /usr/bin/env for any executable that the user would want? That would be consistent, and it's no different from looking for the shell in the environment.

2. In the example you provided, you showed something like bash <script>.sh. But in this case, if you are specifying the executable directly, the shebang is useless. I can write a script like this:

```
#!/usr/bin/env python

echo "HELLO"
```
And then run it with bash

```
$ /bin/bash script.py
HELLO
```
and it works fine, and this is because the shebang isn't needed if I specify the executable directly. On the other hand, if I want the shebang to actually be meaningful, I would need to execute it (and then I'd hit an error)

```bash
./script.py
  File "./script.py", line 3
    echo "HELLO"
               ^
SyntaxError: invalid syntax
```
So the examples you are providing that warrant a shabang _and_ an executable aren't logical to me. I think we should choose one, optimize and stick with it, and the other isn't super important (e.g., the shebang).

**Comment by shahzebsiddiqui** [comment]
We definitely need shebang in order for ``modules`` to work in script this is required for Lmod and documented in FAQ https://lmod.readthedocs.io/en/latest/040_FAQ.html 
See FAQ **Why doesn’t the module command work in shell scripts?**. 

modules are going to be important foreseeable future so buildtest would need to get this right in order for users to write test with their modules.

So shell scripts can be run directly provided they have ``+x``. You don't even need shebang for shell scripts you can run it directly, it good practice to add them as start of script.

I think we need to clearly different shebang from how test is executed. Looking at github https://help.github.com/en/actions/reference/workflow-syntax-for-github-actions#using-a-specific-shell i think they must have an ``enum`` for shell type which makes sense but they internally run a a shell command depending on the platform.

I think ``shell`` should be an enum with ``[sh, bash, python]`` to start out. 

What i prefer is to change shell to an object so we have ability to define the name and opts independently. This just address the shebang. 

```
shell:
  name: sh
  opts: -x
```

For python i have seen ``#!/usr/bin/env python`` and ``#!/usr/bin/env python3`` since python or python3 can be found anywhere in $PATH and generally it's installed in shared filesystem with multiple versions. /usr/bin/python is provided for all Linux distros but with RHEL8 this is not the case.

I think it doesn't hurt to add feature to specify the shebang line. Using ``#!/usr/bin/env`` can have unintended consequence due to $PATH. This would not work depending on what is in user path, it does provide the flexibility but imagine if one python instance works because it was running Anaconda but the other doesn't because not it's using a different python interpreter or system python.

**Comment by shahzebsiddiqui** [comment]
Here are few examples

```
shell:
  shebang: #!/usr/bin/env python
```
```
shell:
  shebang: #!/usr/bin/env python3
```


This one below detects shebang based on python using ``shutil.which()``
```
shell:
  name: python
```

Shebang with options, using ``shebang`` and ``name`` both are equivalent 

```
shell:
  opts: -x
  shebang: #!/bin/bash
```

```
shell:
  opts: -x
  name: bash
```

I think we can make a distinction stating that if you use ``name: sh`` this will run the script with the shell
so ``sh /path/to/script.sh`` whereas using ``shebang`` this will run the script directly ``/path/to/script.sh``

**Comment by vsoch** [comment]
If this is intended and needed for modules, then it needs to be a special case for the slurm (or other modules) executor. For non-module use cases if it doesn't matter, it's noise and confusing to add it.

**Comment by vsoch** [comment]
And if the user has extreme preference for opts, they can write their own script that sets those opts. We don't need to hard code some custom variable that is more confusing than anything to support that.

**Comment by shahzebsiddiqui** [comment]
> If this is intended and needed for modules, then it needs to be a special case for the slurm (or other modules) executor. For non-module use cases if it doesn't matter, it's noise and confusing to add it.

The issue is not specific to slurm, its how ``module`` is setup. It's a wrapper to bash function and it is an issue when you are in one of the shell instances i believe  non-login + non-interactive case where ``module`` command is not found. Anyhow, i have never really understood this clearly and just go with Robert mentions to simply add the shebangs in all your job scripts.  

I think buildtest can figure out the shebang automatically, but still allow user to specify it if they desire. At the moment, i would see myself change the shebang line to test with different options.

**Comment by shahzebsiddiqui** [comment]
I think the way we run tests ``/bin/bash /path/to/script.sh`` that is figured out in Buildtest needs to be clear , this makes sense when running via LocalExecutor but with SlurmExector we would not be running as ``/bin/bash /path/to/script`` but rather ``sbatch /path/to/script.sh``

Furthermore, we don't have any way to pass options to bash on command line.

```
# run test in debug mode
bash -x script.sh
# run test in login shell
bash -l script.sh
```

**Comment by vsoch** [comment]
Then is the shebang important at all? If the shebang isn't important and we want to honor what a user provides for the shell, it's fairly straight forward to be able to have a single "shell" variable that can take any additional options, still parse for the executable path to have the entire thing, and then pass on the options to honor what the user has provided.

**Comment by shahzebsiddiqui** [comment]
I was just googling to get some difference between shebang vs passing command line option.
I found these links a bit helpful
https://superuser.com/questions/195826/bash-shebang-for-dummies
https://bash.cyberciti.biz/guide/Shebang

what about these examples

```
declare_shell_name:
  type: script
  description: declare shell name to sh
  shell:
    name: sh
  run: hostname

declare_shell_opts:
  type: script
  description: declare shell name to sh
  shell:
    name: sh
    opts: "-e"
  run: hostname

declare_shebang:
  type: script
  description: declare shell name to sh
  shell:
    shebang: "#!/usr/bin/env bash"    
  run: hostname
```

First test runs as ``sh /path/to/test``. Second one runs as ``sh -e /path/to/test``, third one runs as ``/path/to/test``.

The default behavior of shell is not provided would be to run ``/path/to/test.sh`` with ``#!/bin/bash`` as shebang.

**Comment by vsoch** [comment]
I think my preference would be to keep the shell at the top level (no sub keys) and then do like:

```
declare_shell_name:
  type: script
  description: declare shell name to sh
  shell: sh
  run: hostname

declare_shell_opts:
  type: script
  description: declare shell name to sh
  shell: sh -e
  run: hostname

declare_shebang:
  type: script
  description: declare shell name to sh
  shell: bash
  shebang: "#!/usr/bin/env bash" 
  run: hostname
```
That is a flat structure, fairly straight forward, and the user provides arguments for the shell directly to shell. They would be parsed in the same way we do any command - by finding the executable as the first, and then adding the rest at runtime.
