### ISSUE TITLE
schema - script

### ISSUE THREAD

**Issue by shahzebsiddiqui** [HPC-buildtest/schemas#5]
The ``script`` schema is intended to for users or SysAdmin to write any shell script to be run locally on the machine. This will allow user full control over the content of the test script and it will be fairly simple schema. Future improvements can be added. 

The way i see it that user can specify a YAML file with one or more subtest. The `type: script`  instructs buildtest to check a schema not created (`script.json`) that will define the schema content. For this schema it can be as simple as a `script` section that allows user to specify one or more commands.

```
login_node_check:
  type: script
  script: 
    - "ping login1"
    - "ping login2"
    - "ping login3"

slurm_check:
  type: script
  script:
   - "systemctl is-active slurmd"
   - "systemctl is-enabled slurmd | grep enabled"
```

**Comment by vsoch** [comment]
Oh this is very simple, I like it! A few points for discussion. For the type `script` my expectation would be to provide a script, and maybe a filename and arguments. Something like:
```
login_node_check:
  type: script
  executable: /bin/bash 
  script: dothing.sh
```
But that's a terrible design, because as you've captured, we can just allow the user to specify one or more (full commands) to execute to the shell.  But in that case, is it really a script? Or is it more of a shell? I actually like the name "script" for the type, but then for the actual commands, I think this is what is actually happening:

```
login_node_check:
  type: script
  shell: 
    - "ping login1"
    - "ping login2"
    - "ping login3"

slurm_check:
  type: script
  shell:
   - "systemctl is-active slurmd"
   - "systemctl is-enabled slurmd | grep enabled"
```

Here is what I think we might consider modeling it after - [snakemake rules](https://snakemake.readthedocs.io/en/stable/snakefiles/rules.html). So the above looks a bit like .travis.ci in that there is a line for each command. Does this mean they are run async? What if the user wants to write more of a script (like a Singularity recipe section, let me know if you aren't familiar). What if we instead had:

``````
# Shell would be accepted to indicate a single line shell command (or similar)
login_node_check:
  type: script
  shell: "ping login 1"

# Run (akin to snakemake) would be a more full script with multiple lines
slurm_check:
  type: script
  run: |
      systemctl is-active slurmd
      systemctl is-enabled slurmd | grep enabled
```

This gives us flexibility to expand upon the script type, because we've specified actions `shell` and `run` to be more specific actions that are relevant for a script type. The difference I see between shell and run is that (although the run is also using the user default shell) the run section is run as a block / script, while the `shell` lines would be run one after the other (and stop on fail) and could potentially be run async if we make a multiprocess worker.

```
